version: '3.9'

services:
  client:
    container_name: client
    ports:
      - 3000:3000
    build:
      context: /client
      dockerfile: Dockerfile
    depends_on:
      - server
    restart: always
  
  server:
    container_name: server
    ports:
      - 3200:3200
    build:
      context: /server
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: always
  
  database:
    container_name: database
    ports:
      - 3306:3306
    build:
      context: /database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/api-service-builder.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    hostname: db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database

volumes:
  mysql-data: